spring:
  application:
    name: validador-temp

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,prometheus
  endpoint:
    health:
      show-details: always
  stackdriver:
    metrics:
      export:
        projectId: ${GOOGLE_CLOUD_PROJECT:validador-temp}
  metrics:
    export:
      stackdriver:
        enabled: true
        project-id: ${GOOGLE_CLOUD_PROJECT:validador-temp}