name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build com Maven
        run: mvn clean verify

      - name: Análise no SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Necessário para PRs
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Seu token do SonarCloud
        with:
          args: >
            -Dsonar.projectKey=thiagorafaelferreira_validador-temp
            -Dsonar.organization=ferreira-codando
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
