# .github/workflows/deploy.yml
name: Deploy to GCP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/validador-temp:latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Debug auth (remover depois que funcionar)
        run: |
          gcloud auth list
          gcloud config list
          echo "Project ID: ${{ secrets.GCP_PROJECT_ID }}"

      - name: Configure Docker
        run: gcloud auth configure-docker

      # Build Docker image
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      # Tag Docker image with GCR URI
      - name: Tag Docker image
        run: docker tag $IMAGE_NAME $IMAGE_NAME

      # Push Docker image to Container Registry
      - name: Push Docker image
        run: docker push $IMAGE_NAME

      # Deploy Docker image to Cloud Run
      - name: Deploy Docker image to Cloud Run
        run: gcloud run deploy validador-temp --image $IMAGE_NAME --region us-central1 --memory 512Mi --min-instances 0 --max-instances 1 --platform managed --port 8080
