# .github/workflows/deploy.yml
name: Deploy to GCP

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Debug auth (remover depois que funcionar)
        run: |
          gcloud auth list
          gcloud config list
          echo "Project ID: ${{ secrets.GCP_PROJECT_ID }}"

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Deploy to Cloud Run
        run: |
          gcloud builds submit --config=cloudbuild.yaml
          gcloud run deploy my-app \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-app \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated